export const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard:view",

  STUDENT_LIST: "students:list",
  STUDENT_CREATE: "students:create",
  STUDENT_READ: "students:read",
  STUDENT_UPDATE: "students:update",
  STUDENT_DELETE: "students:delete",
  STUDENT_TRANSFER: "students:transfer",
  STUDENT_GUARDIAN_MANAGE: "students:guardians:manage",
  STUDENT_DOCUMENT_MANAGE: "students:documents:manage",

  TEACHER_LIST: "teachers:list",
  TEACHER_CREATE: "teachers:create",
  TEACHER_READ: "teachers:read",
  TEACHER_UPDATE: "teachers:update",
  TEACHER_DELETE: "teachers:delete",
  TEACHER_ASSIGNMENT_MANAGE: "teachers:assignments:manage",

  PARENT_LIST: "parents:list",
  PARENT_READ: "parents:read",
  PARENT_CREATE: "parents:create",
  PARENT_UPDATE: "parents:update",
  PARENT_DELETE: "parents:delete",

  STAFF_LIST: "staff:list",
  STAFF_READ: "staff:read",
  STAFF_CREATE: "staff:create",
  STAFF_UPDATE: "staff:update",
  STAFF_DELETE: "staff:delete",

  ACADEMIC_CLASS_LIST: "academic:classes:list",
  ACADEMIC_CLASS_CREATE: "academic:classes:create",
  ACADEMIC_CLASS_READ: "academic:classes:read",
  ACADEMIC_CLASS_UPDATE: "academic:classes:update",
  ACADEMIC_CLASS_DELETE: "academic:classes:delete",
  ACADEMIC_DEPARTMENT_LIST: "academic:departments:list",
  ACADEMIC_DEPARTMENT_CREATE: "academic:departments:create",
  ACADEMIC_DEPARTMENT_READ: "academic:departments:read",
  ACADEMIC_DEPARTMENT_UPDATE: "academic:departments:update",
  ACADEMIC_DEPARTMENT_DELETE: "academic:departments:delete",
  ACADEMIC_SUBJECT_LIST: "academic:subjects:list",
  ACADEMIC_SUBJECT_CREATE: "academic:subjects:create",
  ACADEMIC_SUBJECT_READ: "academic:subjects:read",
  ACADEMIC_SUBJECT_UPDATE: "academic:subjects:update",
  ACADEMIC_SUBJECT_DELETE: "academic:subjects:delete",
  ACADEMIC_SESSION_LIST: "academic:sessions:list",
  ACADEMIC_SESSION_CREATE: "academic:sessions:create",
  ACADEMIC_SESSION_READ: "academic:sessions:read",
  ACADEMIC_SESSION_UPDATE: "academic:sessions:update",
  ACADEMIC_SESSION_DELETE: "academic:sessions:delete",
  ACADEMIC_SECTION_CREATE: "academic:sections:create",
  ACADEMIC_SECTION_UPDATE: "academic:sections:update",
  ACADEMIC_SECTION_DELETE: "academic:sections:delete",
  ACADEMIC_CLASS_SUBJECT_MANAGE: "academic:class-subjects:manage",

  TEACHER_OWN_CLASSES_VIEW: "teachers:own-classes:view",

  ATTENDANCE_STUDENT_MARK: "attendance:student:mark",
  ATTENDANCE_STUDENT_LIST: "attendance:student:list",
  ATTENDANCE_STUDENT_READ: "attendance:student:read",
  ATTENDANCE_STAFF_MARK: "attendance:staff:mark",
  ATTENDANCE_STAFF_LIST: "attendance:staff:list",
  ATTENDANCE_STAFF_READ: "attendance:staff:read",
  ATTENDANCE_OWN_VIEW: "attendance:own:view",

  NOTICE_LIST: "notices:list",
  NOTICE_CREATE: "notices:create",
  NOTICE_UPDATE: "notices:update",
  NOTICE_DELETE: "notices:delete",
  NOTICE_OWN_VIEW: "notices:own:view",

  EXAM_LIST: "exams:list",
  EXAM_CREATE: "exams:create",
  EXAM_UPDATE: "exams:update",
  EXAM_DELETE: "exams:delete",
  EXAM_RESULTS_ENTER: "exams:results:enter",
  EXAM_RESULTS_APPROVE: "exams:results:approve",
  EXAM_OWN_VIEW: "exam:own:view",
  FEE_TYPE_MANAGE: "fees:type:manage",
  FEE_STRUCTURE_MANAGE: "fees:structure:manage",
  FEE_INVOICE_GENERATE: "fees:invoice:generate",
  FEE_INVOICE_LIST: "fees:invoice:list",
  FEE_INVOICE_READ: "fees:invoice:read",
  FEE_PAYMENT_RECORD: "fees:payment:record",
  FEE_DISCOUNT_APPLY: "fees:discount:apply",
  FEE_SCHOLARSHIP_APPLY: "fees:scholarship:apply",
  FEE_RECEIPT_READ: "fees:receipt:read",
  FEE_OWN_VIEW: "fees:own:view",
  ASSIGNMENT_CREATE: "assignments:create",
  ASSIGNMENT_MANAGE: "assignments:manage",
  ASSIGNMENT_GRADE: "assignments:grade",
  ASSIGNMENT_OWN_SUBMIT: "assignments:own:submit",
  ASSIGNMENT_OWN_VIEW: "assignments:own:view",
  ADMISSION_LETTER_VIEW: "admission-letter:own:view",
  MESSAGING_OWN_VIEW: "messaging:own:view",

  PROMOTION_BATCH_RUN: "promotion:batch:run",
  PROMOTION_REVIEW: "promotion:review",
  PROMOTION_VIEW: "promotion:view",

  AUDIT_LOG_READ: "audit:logs:read",
  AUDIT_LOG_EXPORT: "audit:logs:export",

  TIMETABLE_CREATE: "timetable:create",
  TIMETABLE_MANAGE: "timetable:manage",
  TIMETABLE_VIEW: "timetable:view",
  TIMETABLE_OWN_VIEW: "timetable:own:view",
  REPORT_GENERATE: "reports:generate",
  REPORT_OWN_REQUEST: "reports:own:request",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_LABELS: Record<string, string> = {
  SUPER_ADMIN: "Administrator",
  PRINCIPAL: "Principal",
  TEACHER: "Teacher",
  STUDENT: "Student",
};
